### ISSUE TITLE
Out of Memory Issue when train model on Google Colab T4

### ISSUE THREAD

**Issue by ducchung2444** [ArcticHare105/S3Diff#21]
Hi, thank you for sharing this amazing model! I’m facing an issue with training the model on Google Colab with free T4 GPU, and I’m encountering CUDA memory errors. Are there any suggestions or optimizations you recommend to reduce memory usage or make the model trainable on Google Colab?
Here my command:
```bash
accelerate launch --num_processes=4 --gpu_ids="0," --main_process_port 29300 src/train_s3diff.py \
    --sd_path={sd_path} \
    --output_dir="./output" \
    --de_net_path="assets/mm-realsr/de_net.pth" \
    --resolution=128 \
    --train_batch_size=1 \
    --enable_xformers_memory_efficient_attention \
    --viz_freq 25
```
Here the output:
```bash
Steps:   0% 0/50000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/drive/MyDrive/school/semester 7/ML/CuoiKy/S3Diff/src/train_s3diff.py", line 290, in <module>
    main(args)
  File "/content/drive/MyDrive/school/semester 7/ML/CuoiKy/S3Diff/src/train_s3diff.py", line 182, in main
    x_tgt_pred = net_sr(x_src.detach(), deg_score, mixed_tag_prompt)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/school/semester 7/ML/CuoiKy/S3Diff/src/s3diff.py", line 277, in forward
    encoded_control = self.vae.encode(c_t).latent_dist.sample() * self.vae.config.scaling_factor
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 260, in encode
    h = self.encoder(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/autoencoders/vae.py", line 172, in forward
    sample = down_block(sample)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_blocks.py", line 1323, in forward
    hidden_states = resnet(hidden_states, temb=None, scale=scale)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/resnet.py", line 251, in forward
    hidden_states = self.conv2(hidden_states, scale) if not USE_PEFT_BACKEND else self.conv2(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/school/semester 7/ML/CuoiKy/S3Diff/src/model.py", line 49, in my_lora_fwd
    result = result + lora_B(_tmp) * scaling
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB. GPU 0 has a total capacity of 14.75 GiB of which 93.06 MiB is free. Process 44850 has 14.65 GiB memory in use. Of the allocated memory 14.33 GiB is allocated by PyTorch, and 200.60 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

**Comment by ArcticHare105** [comment]
Your setting is already very memory efficient, I can not figure out the issue. However, you need to change `num_processes` to 1 in the training script.
